### PR TITLE
drop Application.StorageId

### PR DESCRIPTION
**Pull request by bacongobbler**
The application name now doubles as the Bindle storage identifier, so if I create an application with the name `bacongobbler/toast-on-demand`, that is the bindle ID that will be passed to the job scheduler.

### CODE REVIEW

**Comment by bacongobbler** [comment]
UpdateAppCommand allows the application name to be changed, but will stop all running jobs. Once a new revision has been registered with the API, it will re-evaluate and re-run the job.

Do we have an idea how we want to handle channels that requested ChannelRevisionSelectionStrategy.UseSpecifiedRevision?

**Comment by itowlson** [comment]
Okay I now have Qualms about this.

Consider a bindle containing a version of WordPress compiled for Wasm (`wordpress/wordpress`).  I want to run two WordPress blogs on my site, one for Anita and one for Bill.  Both use the `wordpress/wordpress` bindle but with different domains and different database connection strings.

How do we model that?  Do I have to make them two channels of the same app?

**Comment by itowlson** [comment]
@bacongobbler No; that comment referred to the scenario where I want to switch the implementation to a new storage ID (e.g. because the vendor rebranded) but keep the application name (e.g. because it is mentioned in several places in my internal support documentation).  Or I want to change the name by which we refer to it because the storage ID is in Polish and Keith from Accounts keeps typoing it when he goes to get the monthly metrics.  That sort of thing.

**Comment by bacongobbler** [comment]
> How do we model that? Do I have to make them two channels of the same app?

I hadn't considered the situation where a user would spin up an instance of someone else's app... I'm not sure how I overlooked that during the meeting.

In this new model, each user would have to "fork" wordpress for each instance, so Bill would re-push `wordpress/wordpress` to `bill/wordpress` and Sam would push `wordpress/wordpress` to `sam/wordpress`. That seems wrong.

Taking Bartholomew as a real-world example, if I upload it to bindle as `bartholomew`, there can only be one instance of bartholomew in the entire cluster. I don't want to re-upload `bartholomew` to `bacongobbler/bartholomew` just so I can create my own instance.

I guess we still need to keep around both fields.

**Comment by bacongobbler** [comment]
> No; that comment referred to the scenario where I want to switch the implementation to a new storage ID (e.g. because the vendor rebranded) but keep the application name (e.g. because it is mentioned in several places in my internal support documentation). Or I want to change the name by which we refer to it because the storage ID is in Polish and Keith from Accounts keeps typoing it when he goes to get the monthly metrics. That sort of thing.

Gotcha... So maybe we should revert the majority of this change but [retain the UpdateAppCommand change](https://github.com/deislabs/hippo/pull/373/files#diff-501ad5a464e871f666d0418b5f870e3411eddcd7c6036bc2065ad7e86e3ba3b8), checking if the `StorageId` was changed before stopping those jobs.

**Comment by bacongobbler** [comment]
closing in favour of #374

**Comment by itowlson** [comment]
If we revert the removal of StorageID, aren't we back to where we started?  (Where we still have an issue of what to do with running jobs but it seems orthogonal to the original purpose of this PR.)  Or maybe I'm missing something.

My preference would be to pause work on this PR, and rough out the desired user workflows for cases like:

* Instant App (from an existing bindle)
* Prewarmed App (setting up an app in advance that you then deploy into)
* Vendor app (where you don't control the storage ID)
* Multiple deployments of same app
* Rename existing app
* Switch existing app over to new storage ID

("We will punt on this" is of course a valid answer to any of these cases.)

**Pull request closed without merging**
